### ISSUE TITLE
hazelcast-jet-contrib-http 

### ISSUE THREAD

**Issue by yunfeiliu2016** [hazelcast/hazelcast-jet-contrib#106]
my code：
 JetInstance jet = Jet.bootstrappedInstance();
        Pipeline p = Pipeline.create();
        StreamStage<AlertVO> alertVOStreamStage = p.readFrom(HttpListenerSources.httpListener(8067, AlertVO.class))
                .withoutTimestamps();
        alertVOStreamStage.map(log -> entry(log.getId(), format(log)))
        .writeTo(Sinks.logger());
After packaging the jar in idea, upload it to a node in the jet cluster, my jet cluster version is 4.3.and then submit it to the cluster for running. However, the submission fails with the following error:  
2020-11-26 17:19:30,109 [ERROR] [hz.youthful_poitras.cached.thread-4] [.h.j.i.MasterJobContext]: Execution of job 'splunk-alert-to-kafka', execution 0555-3450-2383-0001 failed
	Start time: 2020-11-26T17:19:29.582
	Duration: 527 ms
	To see additional job metrics enable JobConfig.storeMetricsAfterJobCompletion
com.hazelcast.jet.JetException: Exception in ProcessorTasklet{splunk-alert-to-kafka/http-listener[8067]#0}: java.lang.ExceptionInInitializerError
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:304) ~[hazelcast-jet-4.3.jar:4.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_261]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_261]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_261]
Caused by: java.lang.ExceptionInInitializerError
	at io.undertow.Undertow.start(Undertow.java:117) ~[?:?]
	at com.hazelcast.jet.contrib.http.impl.HttpListenerSourceContext.<init>(HttpListenerSourceContext.java:81) ~[?:?]
	at com.hazelcast.jet.contrib.http.HttpListenerSourceBuilder.lambda$build$73a7763c$1(HttpListenerSourceBuilder.java:222) ~[?:?]
	at com.hazelcast.function.FunctionEx.apply(FunctionEx.java:47) ~[hazelcast-jet-4.3.jar:4.3]
	at com.hazelcast.jet.impl.connector.ConvenientSourceP.init(ConvenientSourceP.java:109) ~[hazelcast-jet-4.3.jar:4.3]
	at com.hazelcast.jet.core.AbstractProcessor.init(AbstractProcessor.java:83) ~[hazelcast-jet-4.3.jar:4.3]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.init(ProcessorTasklet.java:230) ~[hazelcast-jet-4.3.jar:4.3]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:289) ~[hazelcast-jet-4.3.jar:4.3]
	... 5 more
Caused by: java.lang.NullPointerException
	at io.undertow.UndertowLogger.<clinit>(UndertowLogger.java:58) ~[?:?]
	at io.undertow.Undertow.start(Undertow.java:117) ~[?:?]
	at com.hazelcast.jet.contrib.http.impl.HttpListenerSourceContext.<init>(HttpListenerSourceContext.java:81) ~[?:?]
	at com.hazelcast.jet.contrib.http.HttpListenerSourceBuilder.lambda$build$73a7763c$1(HttpListenerSourceBuilder.java:222) ~[?:?]
	at com.hazelcast.function.FunctionEx.apply(FunctionEx.java:47) ~[hazelcast-jet-4.3.jar:4.3]
	at com.hazelcast.jet.impl.connector.ConvenientSourceP.init(ConvenientSourceP.java:109) ~[hazelcast-jet-4.3.jar:4.3]
	at com.hazelcast.jet.core.AbstractProcessor.init(AbstractProcessor.java:83) ~[hazelcast-jet-4.3.jar:4.3]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.init(ProcessorTasklet.java:230) ~[hazelcast-jet-4.3.jar:4.3]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:289) ~[hazelcast-jet-4.3.jar:4.3]
	... 5 more
i find the error code is "UndertowLogger.ROOT_LOGGER.infof("starting server: %s", Version.getFullVersionString());" 
and "UndertowLogger ROOT_LOGGER = Logger.getMessageLogger(UndertowLogger.class, UndertowLogger.class.getPackage().getName());"  What could be the reason？

**Comment by yunfeiliu2016** [comment]
**However, it is correct for me to run it directly in idea, so it is very strange**
