### ISSUE TITLE
MongoDBSources.stream fails with Exception on empty projection

### ISSUE THREAD

**Issue by eminn** [hazelcast/hazelcast-jet-contrib#29]
When I tried to play with stream I found interesting behavior - if I set projection for MongoDBSources.stream to empty Document (just new Document()) it fails with Exception:
```
WARNING: [192.168.1.114]:5701 [jet] [3.2-SNAPSHOT] Exception in ProcessorTasklet{stream-source#0}
com.mongodb.MongoCommandException: Command failed with error 40177 (Location40177): 'Invalid $project :: caused by :: specification must have at least one field' on server 127.0.0.1:27017. The full response is {"operationTime": {"$timestamp": {"t": 1565772453, "i": 1}}, "ok": 0.0, "errmsg": "Invalid $project :: caused by :: specification must have at least one field", "code": 40177, "codeName": "Location40177", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1565772453, "i": 1}}, "signature": {"hash": {"$binary": "AAAAAAAAAAAAAAAAAAAAAAAAAAA=", "$type": "00"}, "keyId": {"$numberLong": "0"}}}}
at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:179)
at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:299)
at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255)
at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:444)
at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)
at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:200)
at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)
at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)
at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:243)
at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:234)
at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:137)
at com.mongodb.operation.AggregateOperationImpl$1.call(AggregateOperationImpl.java:196)
at com.mongodb.operation.AggregateOperationImpl$1.call(AggregateOperationImpl.java:192)
at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:462)
at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:406)
at com.mongodb.operation.AggregateOperationImpl.execute(AggregateOperationImpl.java:192)
at com.mongodb.operation.ChangeStreamOperation.execute(ChangeStreamOperation.java:265)
at com.mongodb.operation.ChangeStreamOperation.execute(ChangeStreamOperation.java:55)
at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:179)
at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:132)
at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:86)
at com.hazelcast.jet.contrib.mongodb.MongoDBSourceBuilder$StreamContext.fillBuffer(MongoDBSourceBuilder.java:824)
at com.hazelcast.jet.function.BiConsumerEx.accept(BiConsumerEx.java:43)
at com.hazelcast.jet.impl.connector.ConvenientSourceP.complete(ConvenientSourceP.java:115)
at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:377)
at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:242)
at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:259)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

Aug 14, 2019 10:47:40 AM com.hazelcast.jet.impl.MasterJobContext
SEVERE: [192.168.1.114]:5701 [jet] [3.2-SNAPSHOT] job '02f8-12c7-c140-0001', execution 02f8-12c7-c141-0001: some TerminateExecutionOperation invocations failed, execution might remain stuck: [MemberInfo{address=[192.168.1.114]:5701, uuid=2f7571be-bd1f-4c75-adac-1b3d0e7cef45, liteMember=false, memberListJoinVersion=1}=null]
Aug 14, 2019 10:47:40 AM class com.hazelcast.jet.impl.execution.ProcessorTasklet.ProcessorTasklet{stream-source#0}
SEVERE: [192.168.1.114]:5701 [jet] [3.2-SNAPSHOT] job 'null', execution 02f8-12c7-c141-0001 encountered an exception in Processor.close(), ignoring it
java.lang.NullPointerException
at com.hazelcast.jet.contrib.mongodb.MongoDBSourceBuilder$StreamContext.close(MongoDBSourceBuilder.java:849)
at com.hazelcast.jet.function.ConsumerEx.accept(ConsumerEx.java:43)
at com.hazelcast.jet.impl.connector.ConvenientSourceP.close(ConvenientSourceP.java:175)
at com.hazelcast.jet.impl.execution.ProcessorTasklet.closeProcessor(ProcessorTasklet.java:254)
at com.hazelcast.jet.impl.execution.ProcessorTasklet.close(ProcessorTasklet.java:526)
at com.hazelcast.jet.impl.execution.ExecutionContext.completeExecution(ExecutionContext.java:169)
at com.hazelcast.jet.impl.JobExecutionService.lambda$completeExecution$10(JobExecutionService.java:320)
at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:626)
at com.hazelcast.jet.impl.JobExecutionService.completeExecution(JobExecutionService.java:319)
at com.hazelcast.jet.impl.operation.CompleteExecutionOperation.run(CompleteExecutionOperation.java:79)
at com.hazelcast.spi.Operation.call(Operation.java:170)
at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:407)
at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:434)
at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:648)
at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:633)
at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:592)
at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:256)
at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61)
at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:260)
at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:244)
at com.hazelcast.jet.impl.MasterJobContext.invokeCompleteExecution(MasterJobContext.java:557)
at com.hazelcast.jet.impl.MasterJobContext.onExecuteStepCompleted(MasterJobContext.java:472)
at com.hazelcast.jet.impl.MasterContext.lambda$invokeOnParticipant$1(MasterContext.java:278)
at com.hazelcast.jet.impl.util.Util$2.onFailure(Util.java:178)
at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:254)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```
Setting projection to empty Document works fine for MongoDBSources.batch - it seems to be an issue.

**Comment by gurbuzali** [comment]
This is not an issue, that is how MongoDB expects. For batch we use the API `Collection.find` which queries the documents itself so passing an empty `Document` means give me everything. And for stream we use API `Collection.watch` which queries not the documents but the changes on the documents, so it is `ChangeStreamDocument` which has the actual document as a field with the name `fullDocument`. So you have to pass something like this as a projection
`new Document("fullDocument.val", 1).append("_id", 1)`

`'Invalid $project :: caused by :: specification must have at least one field'`
As the exception states MongoDB expects at least one field for `watch` API.
