### ISSUE TITLE
[Jet Springboot] Client JetInstance cannot be configured by hazelcast.client.config system property which contains URL with protocol

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet-contrib#73]
If system property `hazelcast.client.config` is used to configure Jet client and the URL contains protocol then it tries to find file on incorrect path. It uses `app root path` + `hazelcast.client.config value`. It works correctly if protocol is not used there (in that case it does not try to use `app root path` for some reason).

Example: 
if system property like `System.setProperty("hazelcast.client.config", "file:/home/user/hz-jet-client.xml");` is used and springboot app is running from path `/home/user/path/to/springboot/app` then following expcetion is thrown:
```
...
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.jet.JetInstance]: Factory method 'jetInstance' threw exception; nested exception is com.hazelcast.core.HazelcastException: Config file at '/home/user/path/to/springboot/app/file:/home/user/hz-jet-client.xml' doesn't exist.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	... 124 common frames omitted
Caused by: com.hazelcast.core.HazelcastException: Config file at '/home/user/path/to/springboot/app/file:/home/user/hz-jet-client.xml' doesn't exist.
	at com.hazelcast.internal.config.AbstractConfigLocator.loadSystemPropertyFileResource(AbstractConfigLocator.java:271) ~[hazelcast-jet-4.0.jar:4.0]
	at com.hazelcast.internal.config.AbstractConfigLocator.loadFromSystemProperty(AbstractConfigLocator.java:254) ~[hazelcast-jet-4.0.jar:4.0]
	at com.hazelcast.internal.config.AbstractConfigLocator.loadFromSystemProperty(AbstractConfigLocator.java:221) ~[hazelcast-jet-4.0.jar:4.0]
	at com.hazelcast.jet.impl.config.XmlJetClientConfigLocator.locateFromSystemProperty(XmlJetClientConfigLocator.java:38) ~[hazelcast-jet-4.0.jar:4.0]
	at com.hazelcast.jet.impl.config.ConfigProvider.locateAndGetClientConfig(ConfigProvider.java:97) ~[hazelcast-jet-4.0.jar:4.0]
	at com.hazelcast.jet.Jet.newJetClient(Jet.java:180) ~[hazelcast-jet-4.0.jar:4.0]
	at com.hazelcast.jet.contrib.autoconfigure.HazelcastJetClientConfiguration$HazelcastJetClientConfigFileConfiguration.jetInstance(HazelcastJetClientConfiguration.java:62) ~[hazelcast-jet-spring-boot-starter-2.0.0-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	... 125 common frames omitted
```

**Comment by olukas** [comment]
It seems to work correctly if `classpath` protocol is used.

**Comment by olukas** [comment]
It does not work also for `hazelcast.config` with `file` protocol. However it works if `classpath` protocol is used.

**Comment by gurbuzali** [comment]
When you configure the system property `hazelcast.client.config` the jet starter just checks that it is configured and starts a Jet client like this `Jet.newJetClient()`. It expects the the client config locator to find the configured configuration file. See from `AbstractConfigLocator`:

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/config/AbstractConfigLocator.java#L251
```
            if (configSystemProperty.startsWith("classpath:")) {
                loadSystemPropertyClassPathResource(configSystemProperty);
            } else {
                loadSystemPropertyFileResource(configSystemProperty);
            }
```

When you check `loadSystemPropertyClassPathResource`, you can see that it removes the protocol part and tries to find the resource with the rest of the configuration string. But for `loadSystemPropertyFileResource`, there is not such thing it creates a `File` using the whole string thus the exception. 

We can say that `file:` protocol is not supported when you configure using system property. This is not related with starter, even below code won't work:

```
        Jet.newJetInstance(new JetConfig().configureHazelcast(hzConfig -> hzConfig.setClusterName("boot-starter")));
        System.setProperty("hazelcast.client.config", "file:hazelcast-jet-client-specific.xml");
        Jet.newJetClient();
```

**Comment by olukas** [comment]
What can be confusing here for user is that it is not consistent between Jet and IMDG part of config of Jet server. It works for `hazelcast.jet.config` and doesn't work for the others. 

I understand that it cannot be fixed on starter side, but we should at least document it as you suggested since it can be really confusing. For example this will work:
```
-Dhazelcast.jet.config=file:path/to/hazelcast-jet.xml -Dhazelcast.config=path/to/hazelcast.xml
```
but this will fail:
```
-Dhazelcast.jet.config=file:path/to/hazelcast-jet.xml -Dhazelcast.config=file:path/to/hazelcast.xml
```
