### ISSUE TITLE
Http sink intermittently fails if it is run in cluster

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet-contrib#92]
In case when Jet cluster is used for running job with http sink (with `ServerSent`) then it intermittently (in ~50% cases) fails with following exception after job is started:  

Job failed with:
```
08:58:41.291 [ERROR] [c.h.j.i.MasterJobContext] Execution of job '04e0-07d9-da00-0001', execution 04e0-07da-6080-0001 failed
	Start time: 2020-08-27T08:58:40.746
	Duration: 545 ms
	To see additional job metrics enable JobConfig.storeMetricsAfterJobCompletion
com.hazelcast.jet.JetException: Exception in ProcessorTasklet{serverSent@8081#1}: java.lang.IllegalStateException: This vertex has a total parallelism of one and as such only expects input on a specific node. Edge configuration must be adjusted to make sure that only the expected node receives any input. Unexpected input received from ordinal 0: SimpleEvent(timestamp=08:58:41.000, sequence=0)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:373)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:803)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:346)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: This vertex has a total parallelism of one and as such only expects input on a specific node. Edge configuration must be adjusted to make sure that only the expected node receives any input. Unexpected input received from ordinal 0: SimpleEvent(timestamp=08:58:41.000, sequence=0)
	at com.hazelcast.jet.core.ProcessorMetaSupplier$2$1.tryProcess(ProcessorMetaSupplier.java:308)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:187)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:591)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:109)
	at com.hazelcast.jet.impl.processor.ProcessorWrapper.process(ProcessorWrapper.java:93)
	at com.hazelcast.jet.impl.pipeline.FunctionAdapter$AdaptingProcessor.process(FunctionAdapter.java:226)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.processInbox(ProcessorTasklet.java:414)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:289)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:284)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:266)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:366)
	... 3 more
```

Exception from cluster where sink is not run (it can be master node)
```
java.lang.IllegalStateException: This vertex has a total parallelism of one and as such only expects input on a specific node. Edge configuration must be adjusted to make sure that only the expected node receives any input. Unexpected input received from ordinal 0: SimpleEvent(timestamp=08:58:41.000, sequence=0)
	at com.hazelcast.jet.core.ProcessorMetaSupplier$2$1.tryProcess(ProcessorMetaSupplier.java:308)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:187)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:591)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:109)
	at com.hazelcast.jet.impl.processor.ProcessorWrapper.process(ProcessorWrapper.java:93)
	at com.hazelcast.jet.impl.pipeline.FunctionAdapter$AdaptingProcessor.process(FunctionAdapter.java:226)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.processInbox(ProcessorTasklet.java:414)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:289)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:284)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:266)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:366)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:803)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:346)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Originally I thought that it failed based on the fact whether source and sink processors are running on different nodes. However it seems to be independent on that - sometimes it fails if they are on the same nodes and sometimes it fails if they are on different nodes.

**Steps to reproduce:**
As Jet nodes I used 2 AWS instances (with addresses `172.30.0.73` and `172.30.0.127`) and started Jet by:
```
JetConfig config = new JetConfig();
NetworkConfig networkConfig = config.getHazelcastConfig().getNetworkConfig();
JoinConfig join = networkConfig.getJoin();
join.setMulticastConfig(new MulticastConfig().setEnabled(false));
join.setTcpIpConfig(new TcpIpConfig().setEnabled(true)
        .addMember("172.30.0.127:5701")
        .addMember("172.30.0.73:5701"));
JetInstance jet = Jet.newJetInstance(config);
```

Job is sent by Jet client and is following:
```
Pipeline p = Pipeline.create();
StreamSource<SimpleEvent> source = TestSources.itemStream(1);

Sink<Object> sink = HttpListenerSinks.builder()
        .hostFn(() -> {
            Enumeration<NetworkInterface> networkInterfaces = NetworkInterface.getNetworkInterfaces();
            while (networkInterfaces.hasMoreElements()) {
                NetworkInterface networkInterface = networkInterfaces.nextElement();
                Enumeration<InetAddress> inetAddresses = networkInterface.getInetAddresses();
                while (inetAddresses.hasMoreElements()) {
                    InetAddress inetAddress = inetAddresses.nextElement();
                    if (inetAddress.isLoopbackAddress()) {
                        continue;
                    }
                    String hostname = inetAddress.getHostName();
                    if (hostname.contains("172")) {
                        return inetAddress.getHostName();
                    }
                }
            }
            throw new IllegalStateException("No available network interface");
        })
        .accumulateItems(10)
        .buildServerSent();

p.readFrom(source)
        .withoutTimestamps()
        .writeTo(sink);

JetClientConfig config = new JetClientConfig();
ClientNetworkConfig networkConfig = config.getNetworkConfig();
List<String> addresses = new ArrayList<>();
addresses.add("172.30.0.127:5701");
addresses.add("172.30.0.73:5701");
networkConfig.setAddresses(addresses);
JetInstance jet = Jet.newJetClient(config);

JobConfig jc = new JobConfig();
jc.addClass(Main.class);
Job job = jet.newJob(p, jc);
```

**Comment by gurbuzali** [comment]
should be fixed via https://github.com/hazelcast/hazelcast-jet-contrib/pull/23/commits/e89776cd4121a6533ccc637fb344f2e962ebd5f3
