### ISSUE TITLE
com.hazelcast.jet.contrib.twitter.TwitterSourceTest.testStream_userFilter

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet-contrib#95]
_master_ (commit 9a85a541eb06a198f1579f8b9bb36ef5993d8dd4)

Failed on Oracle JDK 8: http://jenkins.hazelcast.com/job/jet-contrib-nightly/192/testReport/junit/com.hazelcast.jet.contrib.twitter/TwitterSourceTest/testStream_userFilter/

Stacktrace:
```
java.lang.AssertionError: Job was expected to complete with AssertionCompletedException, but completed with: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{assertCollectedEventually#0}: java.lang.AssertionError: java.lang.AssertionError: Expected 'Emits at least 15 tweets in 1 min.' to be greater than or equal to 15, but was 12
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.jet.contrib.twitter.TwitterSourceTest.testStream_userFilter(TwitterSourceTest.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Hiccups measured while running test 'testStream_userFilter(com.hazelcast.jet.contrib.twitter.TwitterSourceTest):'
01:11:45, accumulated pauses: 39 ms, max pause: 3 ms, pauses over 1000 ms: 0
01:11:50, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:11:55, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:12:00, accumulated pauses: 31 ms, max pause: 1 ms, pauses over 1000 ms: 0
01:12:05, accumulated pauses: 34 ms, max pause: 2 ms, pauses over 1000 ms: 0
01:12:10, accumulated pauses: 41 ms, max pause: 4 ms, pauses over 1000 ms: 0
01:12:15, accumulated pauses: 30 ms, max pause: 2 ms, pauses over 1000 ms: 0
01:12:20, accumulated pauses: 55 ms, max pause: 2 ms, pauses over 1000 ms: 0
01:12:25, accumulated pauses: 32 ms, max pause: 1 ms, pauses over 1000 ms: 0
01:12:30, accumulated pauses: 43 ms, max pause: 2 ms, pauses over 1000 ms: 0
01:12:35, accumulated pauses: 40 ms, max pause: 3 ms, pauses over 1000 ms: 0
01:12:40, accumulated pauses: 37 ms, max pause: 2 ms, pauses over 1000 ms: 0
01:12:45, accumulated pauses: 33 ms, max pause: 2 ms, pauses over 1000 ms: 0
01:12:50, accumulated pauses: 10 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

**Comment by ufukyilmaz** [comment]
Rarely, the client gets fewer tweets and this makes the test fail, but there seems to be no way to improve it. I can reduce the number of tweets I assert to be fetched but the same can happen no matter how much I reduce it. Since this test didn't fail for a long time after this failure and it failed for once since this test was added (these show that the number of tweets selection is not bad), I close the issue.
